agents:
- agent_id: agent1
  agent_port: 5000
  profile: agent1 is a pragmatic team member. agen1 prefers doing more actual work
    rather than talking.
  type: BaseAgent
- agent_id: agent2
  agent_port: 5001
  profile: agent2 is a talkative team member. agent2 talks more than doing actual
    work.
  type: BaseAgent
- agent_id: agent3
  agent_port: 5002
  profile: agent3 is a judgmental team member. agent3 likes making reflections and
    criticizing team members.
  type: BaseAgent
coordinate_mode: graph
engine_planner:
  initial_progress: Starting the simulation.
environment:
  host: localhost
  max_iterations: 10
  name: Minecraft Environment
  port: 25565
  task_id: 92
  task_name: test
  type: Minecraft
llm: gpt-4o-mini
memory:
  type: SharedMemory
metrics:
  evaluate_llm:
    model: gpt-3.5-turbo
    provider: openai
output:
  file_path: result/minecraft/discussion_output_gpt-4o-mini.jsonl
relationships:
- - agent1
  - agent2
  - collaborate with
- - agent1
  - agent3
  - collaborate with
- - agent2
  - agent3
  - collaborate with
task:
  content: "This is in the game of Minecraft. Build a building according to a blueprint.\
    \ The blueprint contains necessary information about the material, facing direction\
    \ and position of each block.\n*** The minecraft knowledge card ***\nHere are\
    \ some knowledge about minecraft:\n1. The minecraft world x,z is the horizontal\
    \ coordinate, y is the vertical coordinate. y=-61 is the ground level.\n2. You\
    \ can use the tool or empty hand to dig the block, and place the block to the\
    \ world.\n3. You can find the item in the chest. Item in the chest can not directly\
    \ be seen or used, take it out and use it or equip it.\n4. If their is no items\
    \ in the chest, maybe you can find the item at other chest or get it from other\
    \ agent or dig it up or craft it.\n5. One bucket can hold one item, if you want\
    \ to get more items, you need to get more buckets at first.\n6. You are in a team\
    \ with other agents, you can try to find the item from other agents, and do not\
    \ change the blocks other agents placed without permission.\n*** The blueprint\
    \ ***\n[\n    \"[material:gravel facing:A positions:[start:[-13 -60 -3] end:[-8\
    \ -60 -3] start:[-13 -60 -2] end:[-13 -60 -2] start:[-12 -60 -2] end:[-12 -60\
    \ -2] start:[-11 -60 -2] end:[-11 -60 -2] start:[-9 -60 -2] end:[-8 -60 -2] start:[-13\
    \ -60 -1] end:[-13 -60 -1] start:[-9 -60 -1] end:[-8 -60 -1] start:[-13 -60 0]\
    \ end:[-13 -60 0] start:[-10 -60 0] end:[-10 -60 0] start:[-9 -60 0] end:[-8 -60\
    \ 0] start:[-13 -60 1] end:[-13 -60 1] start:[-12 -60 1] end:[-12 -60 1] start:[-10\
    \ -60 1] end:[-10 -60 1] start:[-9 -60 1] end:[-8 -60 1] start:[-13 -60 2] end:[-13\
    \ -60 2] start:[-11 -60 2] end:[-11 -60 2] start:[-10 -60 2] end:[-10 -60 2] start:[-8\
    \ -60 2] end:[-8 -60 2] start:[-12 -60 3] end:[-9 -60 3] start:[-11 -59 -2] end:[-11\
    \ -59 -2] start:[-11 -59 -1] end:[-10 -59 -1] start:[-12 -59 0] end:[-12 -59 0]\
    \ start:[-9 -59 1] end:[-9 -59 1] start:[-11 -58 -1] end:[-11 -58 -1]]]\",\n \
    \   \"material: magma_block facing: A position: [-11, -60, 0]\",\n    \"[material:obsidian\
    \ facing:A position:[-10 -60 -2] material:sand facing:A positions:[[-12 -60 -1]\
    \ [-11 -60 -1] [-10 -60 -1] [-12 -60 0] [-9 -60 2]] material:cobblestone facing:A\
    \ position:[-11 -60 1] material:chiseled_stone_bricks facing:A position:[-10 -59\
    \ -3]]\",\n    \"material: structure_block facing: A position: [-12, -60, 2]\"\
    ,\n    \"[material:cracked_stone_bricks facing:A positions:[[-11 -59 1] [-12 -59\
    \ 2] [-12 -58 2] [-12 -57 2]]]\",\n    \"[material:cracked_stone_bricks facing:A\
    \ positions:[start:[-12 -59 -1] end:[-9 -59 -1] start:[-12 -58 -1] end:[-9 -58\
    \ -1] start:[-12 -57 -1] end:[-9 -57 -1] start:[-13 -56 -1] end:[-8 -56 -1] start:[-11\
    \ -55 -1] end:[-10 -55 -1]]]\",\n    \"[material:cracked_stone_bricks facing:A\
    \ positions:[[-9 -59 2] [-9 -58 2]]]\",\n    \"[material:stone_brick_stairs positions:[coords:[-12\
    \ -55 -1] facing:E coords:[-9 -55 -1] facing:W]]\"\n]"
