agents:
- agent_id: agent1
  agent_port: 5000
  profile: agent1 is a pragmatic team member. agen1 prefers doing more actual work
    rather than talking.
  type: BaseAgent
- agent_id: agent2
  agent_port: 5001
  profile: agent2 is a talkative team member. agent2 talks more than doing actual
    work.
  type: BaseAgent
- agent_id: agent3
  agent_port: 5002
  profile: agent3 is a judgmental team member. agent3 likes making reflections and
    criticizing team members.
  type: BaseAgent
coordinate_mode: graph
engine_planner:
  initial_progress: Starting the simulation.
environment:
  host: localhost
  max_iterations: 10
  name: Minecraft Environment
  port: 25565
  task_id: 85
  task_name: test
  type: Minecraft
llm: together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
memory:
  type: SharedMemory
metrics:
  evaluate_llm:
    model: gpt-3.5-turbo
    provider: openai
output:
  file_path: result/minecraft/discussion_output_llama-31-8b.jsonl
relationships:
- - agent1
  - agent2
  - collaborate with
- - agent1
  - agent3
  - collaborate with
- - agent2
  - agent3
  - collaborate with
task:
  content: "This is in the game of Minecraft. Build a building according to a blueprint.\
    \ The blueprint contains necessary information about the material, facing direction\
    \ and position of each block.\n*** The minecraft knowledge card ***\nHere are\
    \ some knowledge about minecraft:\n1. The minecraft world x,z is the horizontal\
    \ coordinate, y is the vertical coordinate. y=-61 is the ground level.\n2. You\
    \ can use the tool or empty hand to dig the block, and place the block to the\
    \ world.\n3. You can find the item in the chest. Item in the chest can not directly\
    \ be seen or used, take it out and use it or equip it.\n4. If their is no items\
    \ in the chest, maybe you can find the item at other chest or get it from other\
    \ agent or dig it up or craft it.\n5. One bucket can hold one item, if you want\
    \ to get more items, you need to get more buckets at first.\n6. You are in a team\
    \ with other agents, you can try to find the item from other agents, and do not\
    \ change the blocks other agents placed without permission.\n*** The blueprint\
    \ ***\n[\n    \"[material:gravel facing:A shape:rectangle corners:[[-10 -60 -3]\
    \ [-8 -60 3]]]\",\n    \"[material:gravel facing:A positions:[[-11 -60 0] [-11\
    \ -60 1] [-11 -60 2]]]\",\n    \"[material:magma_block facing:A positions:[[-13\
    \ -60 0] [-10 -60 1]]]\",\n    \"[material:gravel facing:A positions:[[-13 -60\
    \ -2] [-12 -60 -3] [-12 -60 -2] [-12 -60 -1] [-12 -60 0] [-12 -60 1] [-12 -60\
    \ 2] [-12 -60 3] [-13 -60 -1] [-13 -60 1] [-13 -60 2] [-13 -60 3] [-11 -60 -3]\
    \ [-11 -60 -1] [-11 -60 3] [-11 -59 -2]]]\",\n    \"[material:structure_block\
    \ facing:A positions:[[-11 -60 -2] [-10 -59 -1] [-11 -59 2]]]\",\n    \"[material:stone_bricks\
    \ facing:A positions:[[-12 -59 -1] [-11 -59 1]]]\",\n    \"[material:mossy_cobblestone\
    \ facing:A positions:[[-8 -59 -3] [-9 -59 0] [-9 -58 -2] [-9 -58 1]]]\",\n   \
    \ \"[material:stone_bricks facing:A positions:[[-9 -59 1] [-9 -59 2]]]\",\n  \
    \  \"[material:mossy_cobblestone facing:A positions:[[-12 -59 -2] [-13 -59 1]\
    \ [-12 -59 3] [-11 -59 3]]]\",\n    \"material: stone_bricks facing: A position:\
    \ [-9, -59, -2]\",\n    \"[material:stone_bricks facing:A positions:[[-13 -59\
    \ 3] [-13 -58 3]]]\",\n    \"material: stone_bricks facing: A position: [-12,\
    \ -58, -1]\",\n    \"material: stone_bricks facing: A position: [-9, -58, 2]\"\
    \n]"
