openai_api_key: "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"
system_prompt_path: marble\\agent\\werewolf_prompts\\system_prompt.yaml
roles:
  - wolf
  - wolf
  - wolf
  - villager
  - villager
  - villager
  - seer
  - witch
  - guard
randomize_roles: True
use_random_names: True
